TeacherJournal.Core/Models/ErrorViewModel.cs
using System;

namespace TeacherJournal.Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TeacherJournal.Core/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;

namespace TeacherJournal.Core.Models
{
    public class StudentViewModel
    {
        public int ID {get; set;}
        public int SubjectID {get; set;}
        public string FirstName {get; set;}
        public string LastName {get; set;}
        public Dictionary<string, List<int?>> Marks {get; set;}
    }
}

TeacherJournal.Core/Models/SubjectViewModel.cs
using System;

namespace TeacherJournal.Core.Models
{
    public class SubjectViewModel
    {
        public int SubjectID { get; set; }
        public int StudentID {get; set;}
        public string Name { get; set; }
        public int Mark {get; set;}
    }
}

TeacherJournal.Core/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using TeacherJournal.BusinessLogic;

namespace TeacherJournal.Core.Controllers
{
    public class LoginController : Controller
    {
        private readonly TeacherService _teacherService;

        public LoginController(TeacherService teacherSerivce)
        {
            _teacherService = teacherSerivce;
        }
        // GET: Index
        public IActionResult Index()
        {
            return View();
        }

        // POST: Index
        [HttpPost]
        public async Task<IActionResult> Index(string login, string password)
        {
            if(await _teacherService.IsAuthenticated(login, password))
            {
                var claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, login)
                };

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaims(claims);

                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    principal, 
                    new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(20),
                        IsPersistent = false
                    });
                return Redirect("/Student");
            }
            return View();
        }

        // GET: Logout
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("/Login");
        }

        // GET: About
        public IActionResult About()
        {
            return View();
        }

    }
}

TeacherJournal.Core/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TeacherJournal.BusinessLogic;
using TeacherJournal.Core.Models;


namespace TeacherJournal.Core.Controllers
{
    [Authorize]    
    public class StudentController : Controller
    {
        private readonly StudentService _studentService;
        private readonly MarkService _markService;
        
        
        public StudentController(StudentService studentService, MarkService markService)
        {
            _studentService = studentService;
            _markService = markService;
        }

        //GET: Index
        public async Task<IActionResult> Index()
        {
            var students = await _studentService.GetAll();
            return View(students);
        }

        //GET: Details
        public async Task<IActionResult> Details(int? id)
        {
            var student = await _studentService.GetByIdAsync(id);
            
            if(student == null)
                return NotFound();

            var grpMarks = student.Marks
                .GroupBy(m => m.Subject.Name, m => m.Grade)
                .ToDictionary(gdc => gdc.Key, gdc => gdc.ToList());

            var studentViewModel = new StudentViewModel {
                ID = student.ID,  
                FirstName = student.FirstName,
                LastName = student.LastName,
                Marks = grpMarks
            };
            return View(studentViewModel);
        }

        //GET: AddStudent
        public IActionResult AddStudent()
        {
            var student = new Student();
            return View(student);
        }

        //POST: AddStudent
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStudent(Student student)
        {
            await _studentService.Create(student.FirstName, student.LastName);
            return RedirectToAction("Index");
        }

        //GET: DeleteStudent
        public async Task<IActionResult> DeleteStudent(int? id)
        {
            if(id == null)
                return NotFound();
            await _studentService.Remove(id.Value);
            return RedirectToAction("Index");
        }
        
        

    }

}

TeacherJournal.Core/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TeacherJournal.BusinessLogic;
using TeacherJournal.Core.Models;

namespace TeacherJournal.Core.Controllers
{
    [Authorize]
    public class SubjectController : Controller
    {
        private readonly MarkService _markService;
        private readonly SubjectService _subjectService;

        private readonly StudentService _studentService;

        public SubjectController(MarkService markService, SubjectService subjectService, StudentService studentService)
        {
            _markService = markService;
            _subjectService = subjectService;
            _studentService = studentService;
        }

        //GET: AddMark
        public async Task<IActionResult> AddMark(string subjectName, int? studentID, int? newMark)
        {
            var subject = await _subjectService.GetByNameAsync(subjectName);
            if(subject == null) 
                return NotFound();
            if(newMark != null)
            {
                await _markService.Create(studentID, subject.ID, newMark);
            }
            return RedirectToAction("Details", "Student", new {id = studentID});
        }

        //GET: AddSubject
        public IActionResult AddSubject(int? studentID)
        {
            var subjectViewModel = new SubjectViewModel { StudentID = studentID.Value};
            return View(subjectViewModel);
        }

        //POST: AddSubject
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSubject(SubjectViewModel subjectViewModel)
        {
            int subjectID = await GetSubjectId(subjectViewModel.Name);
            await _markService.Create(subjectViewModel.StudentID, subjectID, subjectViewModel.Mark);
            return RedirectToAction("Details", "Student", new {id = subjectViewModel.StudentID});
        }

        //POST: DeleteSubject
        public async Task<IActionResult> DeleteSubject(int? studentID, string subjectName)
        {
            var student = await _studentService.GetByIdAsync(studentID);
            int subjectID = await GetSubjectId(subjectName);
            var marks = student.Marks.Where(m => m.SubjectID == subjectID).ToList();
            await _markService.RemoveGroup(marks);
            return RedirectToAction("Details", "Student", new {id = studentID});
        }
        
        private async Task<int> GetSubjectId(string subjectName)
        {
            int subjectID;
            var subject = await _subjectService.GetByNameAsync(subjectName);
            if(subject == null)   
            {
                subjectID = await _subjectService.Create(subjectName);
            }else 
            {
                subjectID = subject.ID;
            }   
            return subjectID;   
        }

        
    }
}

TeacherJournal.Core/Views/Login/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>This service is kind of virtual teacher journal</p>

TeacherJournal.Core/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Teacher Journal";
}

<h2>Login</h2>

<form method="post">
    <input name="login" placeholder="User name"/>
    <input name="password" type="password" placeholder="Password" />
    <button>Log in</button>
</form>

TeacherJournal.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teacher Journal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        @if(User.Identity.IsAuthenticated) {
            <a asp-area="" asp-controller="Student" asp-action="Index" class="navbar-brand">Teacher Journal</a>
        }else {
            <a asp-area="" asp-controller="Login" asp-action="Index" class="navbar-brand">Teacher Journal</a>
        }
    </div>
    <ul class="nav navbar-nav">
      <li><a asp-area="" asp-controller="Login" asp-action="About">About</a></li>
    </ul>
     @if(User.Identity.IsAuthenticated) {
        <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Login" asp-action="Logout"><span class="glyphicon glyphicon-user"></span>Sign Out</a></li>
        </ul>
     }
  </div>
</nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Teacher Journal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TeacherJournal.Core/Views/Student/AddStudent.cshtml
@model TeacherJournal.BusinessLogic.Student;

<h2>Add Student</h2>

<dd>
    <form asp-controller="Student" asp-action="AddStudent" method="Post">
        <input  asp-for="FirstName" type="text" placeholder="First Name"/>
        <input asp-for="LastName" type="text" placeholder="Last Name" />
        </br>
        </br>        
        <input type="submit" value="Create"/>
    </form>
</dd>

TeacherJournal.Core/Views/Student/Details.cshtml
@model StudentViewModel;

<h2>Marks</h2>
<dd>
    <table class="table">
        <tr>
            <th>Subject name</th>
            <th>Marks</th> 
            <th>Avarage</th>  
            <th>Add</th>            
            <th>Delete</th>            
        </tr>
        <br/>
        @foreach (var item in Model.Marks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Key)
                </td>
                <td>
                    @foreach (var mark in item.Value)
                    {
                        @Html.DisplayFor(modelItem => mark)
                        @if(item.Value.LastOrDefault() != mark)
                        {
                            @Html.Raw(", ")
                        }
                    }
                </td>
                <td>
                    @{
                        var avarage = ((double)item.Value.Sum() / (double)item.Value.Count).ToString("F2");
                       
                    }
                    @Html.DisplayFor(modelItem => avarage) 
                </td>
                <td>
                <form asp-controller="Subject" asp-action="AddMark">
                    Grade: <input name="newMark" type="number" max="6" min="1" />
                    <input hidden="hidden" asp-for="@item.Key" name="subjectName" type="text"/>  
                    <input hidden="hidden" asp-for="@Model.ID" name="studentID" type="number"/>                                                          
                    <input type="submit" value="Add"/>
                </form>
                </td>
                <td>
                    <a asp-controller="Subject" asp-action="DeleteSubject" 
                        asp-route-studentID="@Model.ID"
                        asp-route-subjectName="@item.Key">
                    <button>
                        x
                    </button>
                    </a>
                </td>
            </tr>
        }
    </table>
    <a asp-controller="Subject" asp-action="AddSubject" asp-route-studentID="@Model.ID">Add Subject</a> 
</dd>

TeacherJournal.Core/Views/Student/Index.cshtml
@model IEnumerable<TeacherJournal.BusinessLogic.Student>

@{
    ViewData["Title"] = "All students";
}

<h2>Students</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstName)</th>
            <th>@Html.DisplayNameFor(model => model.LastName)</th>
            <th></th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> 
                </td>
                <td>
                    <a asp-action="DeleteStudent" 
                            asp-route-id="@item.ID">
                        <button>
                            x
                        </button>
                    </a>
                </td>
            </tr>}
    </tbody>
</table>
<a asp-controller="Student" asp-action="AddStudent">Add Student</a> 

TeacherJournal.Core/Views/Subject/AddSubject.cshtml
@model SubjectViewModel;

<h2>Add Subject</h2>

<dd>
    <form asp-controller="Subject" asp-action="AddSubject" method="Post">
        <input  asp-for="Name" type="text" placeholder="Name"/>
        Grade: <input asp-for="Mark" type="number" max="6" min="1" />
        <input asp-for="StudentID" type="text" hidden="hidden" />  
        <input type="submit" value="Create"/>
    </form>
</dd>